# Generated by Django 5.0.3 on 2024-12-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=15, unique=True)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('usertype', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Staff', 'Staff')], max_length=10)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
