# Generated by Django 5.0.3 on 2024-12-13 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='scheduled_time',
        ),
    ]
