# Generated by Django 5.0.3 on 2024-12-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_route_scheduled_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=20, unique=True)),
                ('capacity', models.PositiveIntegerField()),
                ('bus_type', models.CharField(choices=[('IIUC', 'IIUC'), ('LOCAL', 'Local')], default='LOCAL', max_length=10)),
            ],
        ),
    ]
