# Generated by Django 5.0.3 on 2024-12-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='RRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('waypoints', models.JSONField()),
            ],
        ),
    ]
