# Generated by Django 5.0.3 on 2024-12-15 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rroute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RRoute',
        ),
    ]
