# Generated by Django 5.0.3 on 2024-12-15 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_delete_rroute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Route',
        ),
    ]
