# Generated by Django 5.0.3 on 2024-12-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_delete_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_no', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('waypoints', models.JSONField()),
            ],
        ),
    ]
